  server:
    port: 38105

  spring:
    application:
      name: backend-guide
    cloud:
      openfeign:
        client:
          config:
            RemoteFaqService:
              url:
                http://localhost:38104
    datasource:
      url: jdbc:postgresql://localhost:38121/guide
      username: lgcms
      password: 1234
      driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: false
      database: postgresql
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true
    data:
      redis:
        host: localhost
        port: 38122
        database-lock: 7
        config:
          connectionPoolSize: 10
          connectionMinimumIdleSize: 5
          subscriptionConnectionPoolSize: 5
          subscriptionConnectionMinimumIdleSize: 1
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000

    ai:
      model:
        embedding: bedrock-titan
        chat: bedrock-converse

      bedrock:
        aws:
          region: ap-northeast-2
        titan:
          embedding:
            model: amazon.titan-embed-text-v2:0
            input-type: text

      vectorstore:
        pgvector:
          index-type: HNSW
          distance-type: COSINE_DISTANCE
  #        dimensions: 1536 # openai용
          initialize-schema: true
          table-name: guide_bot_embedded_q
          dimensions: 1024 # 타이탄 임베딩용
  management:
   endpoints:
     web:
       exposure:
         include: prometheus,health,info
   metrics:
     tags:
       application: ${spring.application.name}
