spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  ai:
    openai:
      api-key: sk-abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz # 더미임
    vectorstore:
      pgvector:
        initialize-schema: true
        schema-validation: true
        table-name: guide_bot_embedded_q
        dimensions: 1536
        index-type: hnsw
        distance-type: cosine_distance