server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: lgcms
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  ai:
    model:
      embedding: bedrock-titan
      chat: bedrock-converse
    openai:
      api-key: ${OPENAI_APIKEY}
      embedding:
        enabled: true
        options:
          model: text-embedding-3-small

    bedrock:
      aws:
        region: ap-northeast-2 # 서울리전
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      titan:
        embedding:
          model: amazon.titan-embed-text-v2:0
          input-type: text

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        initialize-schema: true
        schema-validation: true
        table-name: test_guide_bot_embedded_q
        dimensions: 1024 # 타이탄 임베딩용
